  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  camera_holder_position_controller:
    type: effort_controllers/JointPositionController
    joint: camera_holder_joint
    pid: {p: 2.0, i: 0.0, d: 0.0}

  




